services:
  comms:
    image: eightfingers123/aeromaze_systems_dev:arm64
    container_name: comms
    env_file:
      - env/this.env
    ipc: host
    network_mode: host
    command: bash -c "source /workspace/devel/setup.bash && stdbuf -o L roslaunch zmq_comms d2d_comms.launch"

  flight_manage:
    image: eightfingers123/aeromaze_systems_dev:arm64
    container_name: flight_manager
    env_file:
      - env/this.env
    ipc: host
    network_mode: host
    volumes:
      - ../:/mounted_workspace/
    command: bash -c "source /workspace/devel/setup.bash && stdbuf -o L roslaunch flight_manage flight_manage.launch"
