services:
  comms:
    image: eightfingers123/aeromaze_systems_dev:arm64
    container_name: comms
    env_file:
      - env/this.env
    ipc: host
    network_mode: host
    volumes:
      - ../src/zmq_comms/launch:/workspace/src/zmq_comms/launch
      - ../src/zmq_comms/scripts:/workspace/src/zmq_comms/scripts
    command: bash -c "source /workspace/devel/setup.bash && stdbuf -o L roslaunch zmq_comms d2d_comms.launch"

  flight_manage:
    image: eightfingers123/aeromaze_systems_dev:arm64
    container_name: flight_manager
    env_file:
      - env/this.env
    ipc: host
    network_mode: host
    volumes:
      - ../src/flight_manage/launch:/workspace/src/flight_manage/launch
      - ../src/flight_manage/scripts:/workspace/src/flight_manage/scripts
    command: bash -c "source /workspace/devel/setup.bash && stdbuf -o L roslaunch flight_manage flight_manage.launch"
