services:
  fastlio_aligned:
    image: eightfingers123/aeromaze_systems_core_aligned:arm64
    container_name: fastlio_aligned
    ipc: host
    network_mode: host
    volumes:
      - ./core_scripts/:/root/scripts/
      - ./core_configs/:/root/configs/
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    command: bash -c "source /root/sutd_ws/devel/setup.bash && stdbuf -o L roslaunch /root/scripts/aligned_core.launch"